### ISSUE TITLE
test_all.sh result in FAILED messages - related to requested image's platform (linux/amd64) not matching the detected host platform (linux/arm/v7)?

### ISSUE THREAD

**Issue by kyutums** [Esser50K/PiCameleon#11]
I ran test_all.sh to do a test run of the PiCameleon, but got a ton of ERROR and FAILED messages.

Camera is already activated and docker file was built using the included Dockerfile. 

Any chance that the errors are caused by requested image's platform (linux/amd64) not matching the detected host platform (linux/arm/v7)? I received the following warning whenever I run test_all.sh
**WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested**

**Comment by kyutums** [comment]
Sample errors:
```
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1d489e0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Emmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1d67bc0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Emmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1d987d0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
E.mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1d99ac0 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
E
======================================================================
ERROR: test_routine (__main__.TestNetworkStreamingMode)
----------------------------------------------------------------------
```

```

======================================================================
ERROR: test_update_socket_map (__main__.TestNetworkStreamingMode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_network_streaming_mode.py", line 72, in test_update_socket_map
    hostsfile_only_config, {}, return_value=hostsfile_config)
  File "tests/test_network_streaming_mode.py", line 43, in __init__
    super().__init__(config, trigger_responses)
  File "/picameleon/modes/network_streaming.py", line 30, in __init__
    self.streamer = Streamer(self.format, prepend_size=prepend_size, recording_options=recording_options)
  File "/picameleon/streamers/streamer.py", line 53, in __new__
    recording_options = {"resize": SinglePiCamera().resolution, **recording_options}
  File "/picameleon/utils/single_picamera.py", line 23, in __init__
    SinglePiCamera.instance = PiCamera(**args)
  File "/usr/local/lib/python3.7/site-packages/picamerax/camera.py", line 419, in __init__
    self._init_preview()
  File "/usr/local/lib/python3.7/site-packages/picamerax/camera.py", line 700, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/local/lib/python3.7/site-packages/picamerax/renderers.py", line 587, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/local/lib/python3.7/site-packages/picamerax/mmalobj.py", line 2300, in enable
    prefix="Failed to enable connection")
  File "/usr/local/lib/python3.7/site-packages/picamerax/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamerax.exc.PiCameraMMALError: Failed to enable connection: Out of resources

----------------------------------------------------------------------
Ran 5 tests in 0.074s

FAILED (errors=4)
Error: No 'hosts' nor 'hostsfile' in config.
```

**Comment by Esser50K** [comment]
thanks for letting me know!

So I see this error which I will look into: `Error: No 'hosts' nor 'hostsfile' in config.`

But the main issue seems to be `picamerax.exc.PiCameraMMALError: Failed to enable connection: Out of resources`
which happens when another process is already using the camera.

I will look into this shortly and come back.

**Comment by kyutums** [comment]
> 
> 
> thanks for letting me know!
> 
> So I see this error which I will look into: `Error: No 'hosts' nor 'hostsfile' in config.`
> 
> But the main issue seems to be `picamerax.exc.PiCameraMMALError: Failed to enable connection: Out of resources`
> which happens when another process is already using the camera.
> 
> I will look into this shortly and come back.

Thanks! Do you need any additional files or system messages to troubleshoot it? Just holler if  you need anything. :)

**Comment by Esser50K** [comment]
There were some errors in the tests but it is unrelated to this. I fixed them in #12

So just make sure no other program is using the RaspberryPi camera while running the tests (including PiCameleon itself).

Closing for now, feel free to reopen if you find other issues with the tests.

**Comment by kyutums** [comment]
I think the command should be
`docker build -t picameleon:latest .`
instead of 
`docker built -t picameleon:latest .`

**Comment by gabeale** [comment]
Hi, I also noted this typo, however with piZero I get this message and not able to build the image.
What's wrong?
![image](https://user-images.githubusercontent.com/41168339/127885906-72fe798e-ad8e-441a-a29d-150205fb0f78.png)

I also tried docker build -t picameleon:latest -f Dockerfile.zero but I get this error

![image](https://user-images.githubusercontent.com/41168339/127886227-49701142-b120-4718-8896-bc21f77bb6cb.png)

Any suggestion?
Thx

**Comment by kyutums** [comment]
The warning still occurs on a clean installation of RPi (just finished flashing the SD card and one run of apt upgrade).
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

Results though had MUCH fewer FAILs:

`92c21a83289f0202c69c5613b0098de6c183c03b2caa4e5cc1bd5ee4ab40c3e4
Testing files:
test_network_streaming_mode.py
test_streamer.py
test_photo_motion_detector_mode.py
test_base_mode.py
test_mode_executor.py
test_network_serving_mode.py
test_output_holders.py
test_http_trigger_response.py
test_motion_detector_output.py
test_snapshot_trigger_response.py
test_record_to_file_trigger_response.py
test_network_trigger_mode.py
test_client.py
..../usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 5 tests in 2.218s

OK
1.1.1.1 is not connected. Trying to reconnect.
1.1.1.2 is not connected. Trying to reconnect.
Error: No 'hosts' nor 'hostsfile' in config.

....
----------------------------------------------------------------------
Ran 4 tests in 2.593s

OK
Start recording with h264 format, size: (1280, 720), on port 1
started recording on port 1
trying to stop recording on port 1
stopped recording on port 1

..
----------------------------------------------------------------------
Ran 2 tests in 10.708s

OK

.......
----------------------------------------------------------------------
Ran 7 tests in 0.313s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 0.007s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.079s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
Start recording with h264 format, size: (1280, 720), on port 0
started recording on port 0
trying to stop recording on port 0
stopped recording on port 0

.......
----------------------------------------------------------------------
Ran 7 tests in 0.714s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.988s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 2.154s

OK

.
----------------------------------------------------------------------
Ran 1 test in 0.530s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.022s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.078s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside

Traceback (most recent call last):
  File "tests/test_client.py", line 4, in <module>
    from client.client import Client
  File "/picameleon/client/client.py", line 7, in <module>
    from ..outputs import WriterOutputHolder
ValueError: attempted relative import beyond top-level package


picameleon_test
`

**Comment by kyutums** [comment]
The warning still occurs on a clean installation of RPi (just finished flashing the SD card and one run of apt upgrade).

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

Results though had MUCH fewer fails


Testing files:
test_network_streaming_mode.py
test_streamer.py
test_photo_motion_detector_mode.py
test_base_mode.py
test_mode_executor.py
test_network_serving_mode.py
test_output_holders.py
test_http_trigger_response.py
test_motion_detector_output.py
test_snapshot_trigger_response.py
test_record_to_file_trigger_response.py
test_network_trigger_mode.py
test_client.py
..../usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 5 tests in 2.218s

OK
1.1.1.1 is not connected. Trying to reconnect.
1.1.1.2 is not connected. Trying to reconnect.
Error: No 'hosts' nor 'hostsfile' in config.

....
----------------------------------------------------------------------
Ran 4 tests in 2.593s

OK
Start recording with h264 format, size: (1280, 720), on port 1
started recording on port 1
trying to stop recording on port 1
stopped recording on port 1

..
----------------------------------------------------------------------
Ran 2 tests in 10.708s

OK

.......
----------------------------------------------------------------------
Ran 7 tests in 0.313s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 0.007s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.079s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
Start recording with h264 format, size: (1280, 720), on port 0
started recording on port 0
trying to stop recording on port 0
stopped recording on port 0

.......
----------------------------------------------------------------------
Ran 7 tests in 0.714s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.988s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 2.154s

OK

.
----------------------------------------------------------------------
Ran 1 test in 0.530s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.022s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.078s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside

Traceback (most recent call last):
  File "tests/test_client.py", line 4, in <module>
    from client.client import Client
  File "/picameleon/client/client.py", line 7, in <module>
    from ..outputs import WriterOutputHolder
ValueError: attempted relative import beyond top-level package


picameleon_test

**Comment by Esser50K** [comment]
yeah the warning is always there.. not sure how to get rid of it but it's not an issue.

From what I see all tests succeeded with OK (there is no FAIL=. However there is still that issue of a failed import, will fix that one too.

**Comment by Esser50K** [comment]
@gabeale you need to say where docker should look for the dockerfile. You need to specify the `.` to tell it to look in the current directory

**Comment by gabeale** [comment]
@Esser50K thanks I had success!
I got only few warning like this:
![image](https://user-images.githubusercontent.com/41168339/127896572-c8c5f68e-8d9d-41ed-bf9a-db5d89cf71f8.png)

Anyway I'm going to test it and let you know.
Thx again

**Comment by Esser50K** [comment]
Ok this time I also fixed the client tests with #13 
This also fixes a few things in the client itself which is nice :)

**Comment by kyutums** [comment]
@Esser50K , last bit: I think in the README,

`docker built -t picameleon:latest .`

should be

`docker build -t picameleon:latest .`

:)

**Comment by Esser50K** [comment]
how could I forget, done!

**Comment by kyutums** [comment]
test_all.sh seems to be a-okay:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
122358b6da9a3901e56c342bd17c63d62e9d048fc7c170803169eabf7c94ad25
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting picameleon
  Downloading https://www.piwheels.org/simple/picameleon/picameleon-0.0.2-py3-none-any.whl (41 kB)
Installing collected packages: picameleon
Successfully installed picameleon-0.0.2
WARNING: You are using pip version 21.0.1; however, version 21.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python3.7 -m pip install --upgrade pip' command.
Testing files:
test_network_streaming_mode.py
test_streamer.py
test_photo_motion_detector_mode.py
test_base_mode.py
test_mode_executor.py
test_network_serving_mode.py
test_output_holders.py
test_http_trigger_response.py
test_motion_detector_output.py
test_snapshot_trigger_response.py
test_record_to_file_trigger_response.py
test_network_trigger_mode.py
test_client.py
..../usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/unittest/case.py:628: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 5 tests in 2.137s

OK
1.1.1.1 is not connected. Trying to reconnect.
1.1.1.2 is not connected. Trying to reconnect.
Error: No 'hosts' nor 'hostsfile' in config.

....
----------------------------------------------------------------------
Ran 4 tests in 2.593s

OK
Start recording with h264 format, size: (1280, 720), on port 1
started recording on port 1
trying to stop recording on port 1
stopped recording on port 1

..
----------------------------------------------------------------------
Ran 2 tests in 10.115s

OK

.......
----------------------------------------------------------------------
Ran 7 tests in 0.313s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 0.007s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.079s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
Start recording with h264 format, size: (1280, 720), on port 0
started recording on port 0
trying to stop recording on port 0
stopped recording on port 0

.......
----------------------------------------------------------------------
Ran 7 tests in 0.716s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.844s

OK

....
----------------------------------------------------------------------
Ran 4 tests in 2.142s

OK

.
----------------------------------------------------------------------
Ran 1 test in 0.530s

OK

..
----------------------------------------------------------------------
Ran 2 tests in 0.020s

OK

...
----------------------------------------------------------------------
Ran 3 tests in 30.079s

OK
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside
warning: NODE_ADDR not set, streamer won't be reachable from outside

...
----------------------------------------------------------------------
Ran 3 tests in 0.108s

OK


picameleon_test

**Comment by kyutums** [comment]
test_all.py though gives a lot of ModuleNotFoundError errors:

Testing files:
test_network_streaming_mode.py
test_streamer.py
test_photo_motion_detector_mode.py
test_base_mode.py
test_mode_executor.py
test_network_serving_mode.py
test_output_holders.py
test_http_trigger_response.py
test_motion_detector_output.py
test_snapshot_trigger_response.py
test_record_to_file_trigger_response.py
test_network_trigger_mode.py
test_client.py
Traceback (most recent call last):
  File "tests/test_network_streaming_mode.py", line 3, in <module>
    from modes.network_streaming import NetworkStreamingMode
ModuleNotFoundError: No module named 'modes'

Traceback (most recent call last):
  File "tests/test_streamer.py", line 8, in <module>
    from streamers.base import BaseStreamer
ModuleNotFoundError: No module named 'streamers'

Traceback (most recent call last):
  File "tests/test_photo_motion_detector_mode.py", line 4, in <module>
    from modes.photo_motion_detection import PhotoMotionDetection
ModuleNotFoundError: No module named 'modes'

Traceback (most recent call last):
  File "tests/test_base_mode.py", line 4, in <module>
    from modes.base import BaseMode
ModuleNotFoundError: No module named 'modes'

Traceback (most recent call last):
  File "tests/test_mode_executor.py", line 3, in <module>
    from mode_executor.mode_executor import ModeExecutor
ModuleNotFoundError: No module named 'mode_executor'

Traceback (most recent call last):
  File "tests/test_network_serving_mode.py", line 4, in <module>
    from modes.network_serving import NetworkServingMode
ModuleNotFoundError: No module named 'modes'

Traceback (most recent call last):
  File "tests/test_output_holders.py", line 3, in <module>
    from outputs.motion_output_holder import MotionOutputHolder
ModuleNotFoundError: No module named 'outputs'

Traceback (most recent call last):
  File "tests/test_http_trigger_response.py", line 3, in <module>
    from trigger_responses.trigger_response_store import TriggerResponseStore
ModuleNotFoundError: No module named 'trigger_responses'

Traceback (most recent call last):
  File "tests/test_motion_detector_output.py", line 3, in <module>
    from outputs.motion_detector import MotionDetector
ModuleNotFoundError: No module named 'outputs'

E
======================================================================
ERROR: test_trigger_response (__main__.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/mock.py", line 1196, in patched
    arg = patching.__enter__()
  File "/usr/lib/python3.7/unittest/mock.py", line 1252, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.7/unittest/mock.py", line 1422, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.7/unittest/mock.py", line 1105, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'picamerax'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)

Traceback (most recent call last):
  File "tests/test_record_to_file_trigger_response.py", line 3, in <module>
    from streamers.streamer import Streamer, ROOT_PATH
ModuleNotFoundError: No module named 'streamers'

Traceback (most recent call last):
  File "tests/test_network_trigger_mode.py", line 4, in <module>
    from modes.network_trigger import NetowrkTriggerMode
ModuleNotFoundError: No module named 'modes'

...
----------------------------------------------------------------------
Ran 3 tests in 0.110s

OK

**Comment by kyutums** [comment]
Also experienced an odd docker message when I ran `docker run -d --name picameleon --privileged -v /opt/vc:/opt/vc --env LD_LIBRARY_PATH=/opt/vc/lib -e CONFIG_FILE=stream_server_config.json picameleon:latest` right after a reboot.

> pi@raspberrypi:~/PiCameleon $ docker run -d --name picameleon --privileged -v /opt/vc:/opt/vc --env LD_LIBRARY_PATH=/opt/vc/lib -e CONFIG_FILE=stream_server_config.json picameleon:latest
docker: Error response from daemon: Conflict. The container name "/picameleon" is already in use by container "a25a6124ca41275996644c8547b50728d223ab516db3e958934059e654ef4cb9". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

I listed all the containers and got this:

> pi@raspberrypi:~/PiCameleon $ docker ps -a
> CONTAINER ID   IMAGE               COMMAND                  CREATED         STATUS                       PORTS     NAMES
> a25a6124ca41   picameleon:latest   "/bin/sh -c 'python3…"   6 minutes ago   Exited (137) 2 minutes ago             picameleon

**Comment by Esser50K** [comment]
@kyutums 

Hey there! The test_all.py script is not ment to be run like that. The test_all.sh copies it into a container and executes it inside there.

The issue with the docker command is because you have a stopped container with the name "picameleon". You can remove it with `docker rm picameleon`

Or you can run the command giving a different name in the `--name` flag

**Comment by kyutums** [comment]
Thanks @Esser50K for the tips! I'll give those a whirl. :)
